// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH6YEFTWCnCvn3n9LiWY_79zt5dlfBAmU',
    appId: '1:539093851056:web:280a2c0882836d7d21d475',
    messagingSenderId: '539093851056',
    projectId: 'bytebrahmand-codeshastra',
    authDomain: 'bytebrahmand-codeshastra.firebaseapp.com',
    storageBucket: 'bytebrahmand-codeshastra.appspot.com',
    measurementId: 'G-Q3HV35PJEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_G1MuzwsIfHWK56x3cOARPbqaTBQwvg',
    appId: '1:539093851056:android:917197710e34c9ae21d475',
    messagingSenderId: '539093851056',
    projectId: 'bytebrahmand-codeshastra',
    storageBucket: 'bytebrahmand-codeshastra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsx5p8vy0d3lqOprVh0lpr_CkwrzMNd2M',
    appId: '1:539093851056:ios:346be3431eb1c0c521d475',
    messagingSenderId: '539093851056',
    projectId: 'bytebrahmand-codeshastra',
    storageBucket: 'bytebrahmand-codeshastra.appspot.com',
    iosBundleId: 'com.example.bytebrahmandCodeshastra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsx5p8vy0d3lqOprVh0lpr_CkwrzMNd2M',
    appId: '1:539093851056:ios:d5ad40e0b913206921d475',
    messagingSenderId: '539093851056',
    projectId: 'bytebrahmand-codeshastra',
    storageBucket: 'bytebrahmand-codeshastra.appspot.com',
    iosBundleId: 'com.example.bytebrahmandCodeshastra.RunnerTests',
  );
}
